version: "3.8"

services:
  api:  
    build: 
      context: /api/.
      dockerfile: ./Dockerfile 
    env_file: ./envs/api.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api:/app

  postgres:
    image: postgres:latest
    env_file: ./envs/postgres.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: on-failure
